# Generated by Django 5.0 on 2023-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0002_alter_category_options_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images'),
        ),
    ]
