# Generated by Django 5.0 on 2024-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0005_alter_machine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(default='\\machine_images\\machine1.JPG', upload_to=''),
        ),
    ]
