# Generated by Django 5.0 on 2024-02-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0006_alter_machine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='image',
        ),
        migrations.CreateModel(
            name='MachineImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equip_list.machine')),
            ],
        ),
    ]
