# Generated by Django 5.0 on 2024-02-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0008_machine_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mainImage',
            field=models.ImageField(blank=True, default='boo.png', null=True, upload_to='machine_images/'),
        ),
        migrations.AlterField(
            model_name='machineimages',
            name='image',
            field=models.ImageField(upload_to='machine_images/'),
        ),
    ]
