# Generated by Django 5.0 on 2024-02-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0010_machine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images/'),
        ),
    ]
