# Generated by Django 5.0 on 2024-02-16 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0011_alter_machineimages_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineimages',
            options={'verbose_name_plural': 'MachineImages'},
        ),
    ]
