# Generated by Django 5.0 on 2024-02-17 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0013_remove_machineimages_machine_machine_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='images',
        ),
        migrations.AddField(
            model_name='machineimages',
            name='machine',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='equip_list.machine'),
            preserve_default=False,
        ),
    ]
