# Generated by Django 5.0 on 2024-02-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0015_alter_machine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
