# Generated by Django 5.0 on 2024-02-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0016_alter_machine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mainImage',
            field=models.ImageField(default='boo.png', null=True, upload_to='machine_images/'),
        ),
        migrations.AlterField(
            model_name='machineimages',
            name='image',
            field=models.ImageField(null=True, upload_to='machine_images/'),
        ),
    ]
