# Generated by Django 5.0 on 2024-02-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0018_alter_machine_created_by_alter_machine_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
