# Generated by Django 5.0 on 2024-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0021_alter_machine_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mainImage',
            field=models.ImageField(blank=True, default='boo.png', null=True, upload_to='machine_images/'),
        ),
    ]
