# Generated by Django 5.0 on 2024-02-25 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0022_alter_machine_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1960)]),
        ),
    ]
