# Generated by Django 5.0 on 2024-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0023_alter_machine_name_alter_machine_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images/'),
        ),
    ]
