# Generated by Django 5.0 on 2024-02-27 00:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_list', '0024_alter_machineimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip_list.category'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1960)]),
        ),
    ]
